### ISSUE TITLE
Загрузка статики не в родительском шаблоне

### ISSUE THREAD

**Issue by aeonva1ues** [Bananad47/Yandex_lyceum#52]
Было бы лучше, если бы загрузка статики была в базовом шаблоне, т.к в таком случае она сразу будет везде и в отдельных шаблонах не придется это прописывать

https://github.com/Bananad47/Yandex_lyceum/blob/677bcc22c8dd737519673524f5466e86199e99f2/lyceum/templates/homepage/home.html#L6

**Comment by Bananad47** [comment]
статика загружается только на 1 шаблон, это в лекции говорили, сейчас проверил падает, если load static убрать

**Comment by aeonva1ues** [comment]
соглашусь
