### ISSUE TITLE
Сжатую фотографию можешь получать по-другому

### ISSUE THREAD

**Issue by aeonva1ues** [Bananad47/Yandex_lyceum#53]
Думаю в этом и есть причина наплыва запросов (проверю еще конечно)

Внутри цикла в шаблоне находится загрузка thumbnail, вместо этого ты мог воспользоваться методом get_image_300x300.url у объекта товара
`<img src="{{ item.main_image.get_image_300x300.url }}" />`

**Comment by Bananad47** [comment]
я об этом вроде писал , но у меня почему-то так не работает

**Comment by Bananad47** [comment]
[12/Mar/2023 19:52:13] "GET /media/cache/0d/40/0d4063b1ea331c6d713c189f12d24252.jpg HTTP/1.1" 404 13511

не находит почему-то

**Comment by aeonva1ues** [comment]
Всё работает
Видимо у тебя не загружаются фото, загруженные еще до подключения сорла
